# Generated by Django 4.2.3 on 2023-07-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_note_date_created_note_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
