# Generated by Django 4.2.3 on 2023-07-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_alter_note_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='date_modified',
            new_name='dateModified',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='noteText',
        ),
    ]
